language: vim

matrix:
  include:
    # travis build-in vim version, 7.x
    - env: TESTVIM=vim
    # nightly build neovim version
    - env: TESTVIM=nvim

install:
  - |
    set -e
    pushd /tmp
    if [ "$TESTVIM" = nvim ]; then
      curl -LO https://github.com/neovim/neovim/releases/download/v0.4.4/nvim-linux64.tar.gz
      tar xzf nvim-linux64.tar.gz
      export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
    fi
    popd

script:
  - test/run-tests.sh

